### ISSUE TITLE
Sync actions with other players

### ISSUE THREAD

**Issue by MichaelCoding25** [Manvaril/vehcontrol#1]
I would like for the actions, like opening the trunk, hood, rolling down windows etc, to be synced across the players so everyone around me can see that the action has been done, because currently only the player who does the action, can see the effect of it and that is kinda unrealistic in the sense that everyone should be able to see you do those actions.

**Comment by Manvaril** [comment]
this issue after further testing, has not be reproduced. I have tested with other people and they see the changes.
