### ISSUE TITLE
[FEATURE REQUEST] Use fxmanifest.lua

### ISSUE THREAD

**Issue by Davidoff7776** [Manvaril/vehcontrol#10]
**Is your feature request related to a problem? Please describe.**
No. Only that this resource is using a deprecated method.

**Describe the solution you'd like**
Use fxmanifest.lua instead of __resource.lua.

**Describe alternatives you've considered**
There's no alternative.

**Additional context**
No need to.

**Comment by Manvaril** [comment]
This issue is squashed as of today with the release of version 1.1.5
