### ISSUE TITLE
NUI Freezing on Startup

### ISSUE THREAD

**Issue by SHVFD728** [Manvaril/vehcontrol#16]
I have been getting reports from my players that when they startup the game, the NUI menu is open and “ESC” does not close it. I’ve given them instructions to type /vehcontrolclose in the F8 menu but that’s is very intrusive to have to do every time you start the game. Has this been reported or any fixes to be had?

**Comment by SHVFD728** [comment]
EDIT* typing /vehcontrolclose in F8 only closes the NUI but the player is still frozen until they relog.

**Comment by Manvaril** [comment]
Updated the resource with new keybinds, please download and try that, make sure your resource folder is "vehcontrol"
