### ISSUE TITLE
[BUG] Menu Stuck on screen

### ISSUE THREAD

**Issue by giovanniammirati** [Manvaril/vehcontrol#18]
**Describe the bug**
When I open the carcontrol gui with the hotkey any of the buttons work, and when I press the esc key to close it, the mouse arrow is still moving on the screen and I can't control the game. Can you guys help me resolve this issue? Thanks

**Comment by Manvaril** [comment]
Make sure you have renamed the resource to vehcontrol and not vehcontrol-master

**Comment by giovanniammirati** [comment]
Ok that fixed the issue! Thank you.
