### ISSUE TITLE
UI menu not working

### ISSUE THREAD

**Issue by demondeye** [Manvaril/vehcontrol#3]
No functions on the Ui menu are executing.  only the commands are working.  the UI need to fixed since no ui commands are executing and the menu gets stuck when closing and have to use the vehcontrolclose to close the menu down to be able to move again

**Comment by Manvaril** [comment]
make sure you have nothing that is blocking the script, ie: no scripts that alter the vehicles. Try disabling each script that messes with your vehicles one by one till vehControl works.
