### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Rajhab** [Manvaril/vehcontrol#4]
Hey If iam in the Car and i want to take my weapon it doesnt work because the menu that comes can i disable that the menu is open with mousewheelup?
Because its really shit when u want to take out ur weapon

**Comment by Manvaril** [comment]
I went over how to change the hotkeys for VehControl in the comments of the resource posting
Open: https://forum.cfx.re/t/release-standalone-vehcontrol-nui-menu/1746959/52
Close: https://forum.cfx.re/t/release-standalone-vehcontrol-nui-menu/1746959/51

**Comment by Rajhab** [comment]
> I went over how to change the hotkeys for VehControl in the comments of the resource posting
> Open: https://forum.cfx.re/t/release-standalone-vehcontrol-nui-menu/1746959/52
> Close: https://forum.cfx.re/t/release-standalone-vehcontrol-nui-menu/1746959/51

Thank you
