### ISSUE TITLE
[BUG] UI Not working & freezing

### ISSUE THREAD

**Issue by JJPivot** [Manvaril/vehcontrol#5]
Hello, I am having a bit of a hard time having this work. 

I can open up the UI but when I click on the buttons nothing actually happens. When I try to use the commands they do work but just not the UI. Is there any general fix for this?

Also I have been finding that I am needing to do the /vehcontrolclose command more than I would prefer. Is there anything I can do to prevent the UI from freezing?

Thanks

**Comment by Manvaril** [comment]
I can't replicate the problem, even on fresh install of FiveM the menu works perfectly with no issues. Try disabling any scripts that deals with the UI or Vehicles one by one till you narrow down the conflicting script

**Comment by Manvaril** [comment]
This issue was revisited and we discovered that the resource folder was not correctly named, they named the folder "vehcontrol-master" after the github download, when the folder needed to be "vehcontrol" due to the pathing of the menu and NUI.
